#ifndef HAL_WHEELS_WHEELS_CFG_H_
#define HAL_WHEELS_WHEELS_CFG_H_

// Left Wheels Direction
#define WHEELS_LEFT_DIRECTION_PORT      DIO_PORTC
#define WHEELS_LEFT_POSITIVE_PIN        DIO_PIN0
#define WHEELS_LEFT_NEGATIVE_PIN        DIO_PIN1
#define WHEELS_LEFT_SPEED_PIN           PWM_PIN_OC0A

// Right Wheels Direction
#define WHEELS_RIGHT_DIRECTION_PORT     DIO_PORTC
#define WHEELS_RIGHT_NEGATIVE_PIN       DIO_PIN2
#define WHEELS_RIGHT_POSITIVE_PIN       DIO_PIN3
#define WHEELS_RIGHT_SPEED_PIN          PWM_PIN_OC0B

#endif