#ifndef HAL_ULTRASONIC_ULTRASONIC_CFG_H_
#define HAL_ULTRASONIC_ULTRASONIC_CFG_H_

#define ULTRASONIC_TRIGGER_PORT     DIO_PORTD
#define ULTRASONIC_ECHO_PORT        DIO_PORTD
#define ULTRASONIC_ECHO_PIN         DIO_PIN3
#define ULTRASONIC_TRIGGER_PIN      DIO_PIN4

#endif